version: "2"

services:
  awsl-py:
    # build:
    #   context: ../
    #   dockerfile: ./docker/Dockerfile
    image: registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:2.0
    container_name: awsl-py
    environment:
      ENV_FILE: .env
    volumes:
      - ../.env.local:.env
    ports:
        - "8000:8000"

  awsl-task:
    image: registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:2.0
    container_name: awsl-redis
    entrypoint: celery -A awsl_start worker --beat --loglevel=INFO
    restart: always
    environment:
      ENV_FILE: .env
    volumes:
      - ../.env.local:.env

  awsl-bot:
    image: registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:2.0
    container_name: awsl-redis
    entrypoint: python3 bot_start.py
    restart: always
    environment:
      ENV_FILE: .env
    volumes:
      - ../.env.local:.env
