version: "2"

services:

  awsl-task:
    image: registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:2.0
    container_name: awsl-task
    restart: always
    environment:
      ENV_FILE: .env
    volumes:
      - ../.env.local:.env
