name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:2.0
    - name: Push the Docker image
      run: docker push registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:2.0
